/*
 * Copyright 2020 NXP
 * All rights reserved.
 *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef SHIELDS_CELLULAR_IOT_SHIELD_COMMON_H_
#define SHIELDS_CELLULAR_IOT_SHIELD_COMMON_H_

#define CELLULAR_IOT_SHIELD_IS_SKYWIRE (2)
#define CELLULAR_IOT_SHIELD_IS_MONARCHGO_SHIELD (3)

#endif /* SHIELDS_CELLULAR_IOT_SHIELD_COMMON_H_ */
