#ifndef __NBIOT_SHIELD_SKYWIRE_H__
#define __NBIOT_SHIELD_SKYWIRE_H__

#include "board.h"
#include "pin_mux.h"
#include "gm01q_tools.h"
#include "fsl_clock.h"
#include "fsl_reset.h"
#include "FreeRTOS.h"

/* This file cannot be included directly in common code, it must pass through "NBIOT_shield.h" */
#ifndef NBIOTSHIELD_ENABLED
#   define NBIOTSHIELD_ENABLED
#else
#   error "Other NBIOT shield is already enabled !"
#endif

extern usart_rtos_handle_t g_uartRtosHandle;
extern usart_handle_t g_uartHandle;
extern usart_dma_handle_t g_uartDmaHandle;
extern dma_handle_t g_timerTransferHandle;

/* Pinmux function, generated by pinmuxtool */
#define NBIOTSHIELD_PINMUX_INIT BOARD_InitSequansSkywireShield

/* USART settings */
#define NBIOTSHIELD_USART (USART2)
#define NBIOTSHIELD_USART_CLK (kCLOCK_Flexcomm2)
#define NBIOTSHIELD_USART_CLK_CONNECT (kFRO12M_to_FLEXCOMM2)
#define NBIOTSHIELD_USART_IP_RESET (kFC2_RST_SHIFT_RSTn)
#define NBIOTSHIELD_USART_BAUDRATE (921600U)
#define NBIOTSHIELD_USART_IRQ (FLEXCOMM2_IRQn)
#define NBIOTSHIELD_USART_IRQ_MASK (USART_FIFOINTENSET_RXLVL_MASK | USART_FIFOINTENSET_RXERR_MASK)
#define NBIOTSHIELD_USART_IRQ_PRIORITY (configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY)
#define NBIOTSHIELD_USART_RTOS_HANDLE (g_uartRtosHandle)
#define NBIOTSHIELD_USART_HANDLE (g_uartHandle)
#define NBIOTSHIELD_USART_RING_BUFFER (g_rxRingBuffer)
#define NBIOTSHIELD_USART_TX_BUFFER (g_txBuffer)
#define NBIOTSHIELD_USART_RX_BUFFER (g_rxBuffer)
#define NBIOTSHIELD_USART_BUFFER_SIZE (AT_BUFFER_SIZE)
#define NBIOTSHIELD_USART_QUEUE_SIZE (10U)

/* DMA settings */
#define NBIOTSHIELD_DMA (DMA0)
#define NBIOTSHIELD_DMA_RX_CH (10U)
#define NBIOTSHIELD_DMA_TX_CH (11U)
#define NBIOTSHIELD_DMA_SPARE_CH (0U)
#define NBIOTSHIELD_DMA_HANDLE (g_uartDmaHandle)
#define NBIOTSHIELD_DMA_RXHANDLE (g_timerTransferHandle)
#define NBIOTSHILED_DMA_IRQ (DMA0_IRQn)
#define NBIOTSHIELD_DMA_IRQ_PRIORITY (1/*configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY + 1U*/)

#endif
